# Generated by Django 4.2 on 2024-05-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightmandu', '0002_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
