# Generated by Django 4.2 on 2024-05-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightmandu', '0003_route_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_passengers',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
