# Generated by Django 4.2 on 2024-05-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightmandu', '0004_booking_number_of_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pnr',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
